# GitLab CI/CD configuration file

stages:
  - build
  - test
  - deploy

variables:
  BUNDLER_VERSION: "2.3.13"

before_script:
  - gem install bundler --version $BUNDLER_VERSION

install_dependencies:
  stage: build
  script:
    - bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle
    - bundle exec rake login:deploy_json
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/bundle
  artifacts:
    when: on_success
    paths:
      - test-results/

test:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths:
      - test-results/

deploy:
  stage: deploy
  script:
    - make copy_vendor
    - bundle exec rake login:deploy_json
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push ${SPACE}-identity-saml-sinatra -b ruby_buildpack
  only:
    - main
  except:
    - tags
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - vendor/bundle

job_build:
  stage: build
  script:
    - bundle exec rake login:deploy_json
    - make copy_vendor
  only:
    - main

job_test:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths:
      - test-results/

job_deploy:
  stage: deploy
  script:
    - bundle exec rake login:deploy_json
    - make copy_vendor
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push ${SPACE}-identity-saml-sinatra -b ruby_buildpack
  only:
    - main