# Ruby GitLab CI configuration file

variables:
  BUNDLER_VERSION: "2.3.13"

stages:
  - test
  - deploy

install_dependencies:
  stage: test
  image: cimg/ruby:3.1.4-browsers
  script:
    - gem install bundler --version $BUNDLER_VERSION
    - bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle
    - bundle exec rake login:deploy_json
    - yarn install --cache-folder ~/.cache/yarn
  cache:
    key:
      files:
        - Gemfile.lock
        - yarn.lock
    paths:
      - vendor/bundle
      - ~/.cache/yarn

build_release:
  stage: test
  script:
    - bundle exec rake login:deploy_json
    - make copy_vendor

test:
  stage: test
  image: cimg/ruby:3.1.4-browsers
  script:
    - make test
  artifacts:
    paths:
      - /tmp/test-results
    reports:
      junit: /tmp/test-results

deploy_to_cloudgov:
  stage: deploy
  image: cimg/ruby:3.1.4-browsers
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - cf login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push $SPACE-identity-saml-sinatra -b ruby_buildpack
  cache:
    key: identity-saml-sinatra-$CI_COMMIT_REF_SLUG
    paths:
      - vendor/bundle

test_and_deploy:
  stage: test
  script: echo "This job is for testing and deploying"
  only:
    refs:
      - move-identity-saml-sinatra-from-GH-toGL

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "move-identity-saml-sinatra-from-GH-toGL"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "move-identity-saml-sinatra-from-GH-toGL"'
      when: never
  include:
    - template: 'Workflows/Branch-Pipeline.gitlab-ci.yml'
