# Ruby GitLab CI configuration file

variables:
  BUNDLER_VERSION: "2.3.13"

default:
  image: cimg/ruby:3.1.4-browsers

stages:
  - test
  - deploy

install_dependencies:
  stage: test
  image: cimg/ruby:3.1.4-browsers
  script:
    - gem install bundler --version $BUNDLER_VERSION
    - bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/bundle
    - bundle exec rake login:deploy_json
    - yarn install --cache-folder ~/.cache/yarn
  cache:
    key:
      files:
        - Gemfile.lock
        - yarn.lock
    paths:
      - vendor/bundle
      - ~/.cache/yarn

build_release:
  stage: build
  image: cimg/ruby:3.1.4-browsers
  script:
    - *bundle_install
    - bundle exec rake login:deploy_json
    - make copy_vendor

test:
  stage: test
  image: cimg/ruby:3.1.4-browsers
  script:
    - *bundle_install
    - make test
  artifacts:
    paths:
      - /tmp/test-results
    reports:
      junit: /tmp/test-results

deploy_to_cloudgov:
  stage: deploy
  image: cimg/ruby:3.1.4-browsers
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - *bundle_install
    - bundle exec rake login:deploy_json
    - cf login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push $SPACE-identity-saml-sinatra -b ruby_buildpack
  parallel:
    matrix:
      - SPACE: [prod, staging, int, dev]

# Sync from GitHub
include:
  project: 'lg/identity-gitlab'
  ref: 'move-identity-saml-sinatra-from-GH-toGL'
  file: '.gitlab-ci-sync.yml'
