# Ruby GitLab configuration file
#
# Check [GITLAB SITE] for more details
#
default:
  image: ruby:3.1.4

.bundle_install: &bundle_install
  - bundle check || bundle install --deployment --jobs=4 --retry=3 --without deploy development doc production --path vendor/ruby

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby

before_script:
  - bundle config set path 'vendor/ruby'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: ruby:3.1.4
  script:
    - *bundle_install
    - bundle exec rake login:deploy_json

test:
  stage: test
  image: ruby:3.1.4
  script:
    - *bundle_install
    - make test
  artifacts:
    paths:
      - /tmp/test-results

deploy:
  stage: deploy
  image: ruby:3.1.4
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - dpkg -i cf-cli_amd64.deb
    - cf -v
    - *bundle_install
    - bundle exec rake login:deploy_json
    - cf login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $TEST_CF_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf push $SPACE-identity-saml-sinatra
  parallel:
    matrix:
      - SPACE: [dev]


# Sync from GitHub
include:
  project: 'lg/identity-gitlab'
  ref: 'main'
  file: '.gitlab-ci-sync.yml'
