---
assertion_consumer_service_url: <%= ENV['assertion_consumer_service_url'] %>
issuer: <%= ENV['issuer'] %>
idp_sso_target_url: <%= ENV['idp_sso_target_url'] %>
idp_slo_target_url: <%= ENV['idp_slo_target_url'] %>
idp_cert_fingerprint: <%= ENV['idp_cert_fingerprint'] %>

assertion_consumer_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
name_identifier_format: urn:oasis:names:tc:SAML:1.1:nameid-format:persistent
ial_context: http://idmanagement.gov/ns/assurance/ial/1
single_signon_service_binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
allowed_clock_drift: 60
security:
  authn_requests_signed: true
  logout_requests_signed: true
  embed_sign: true
  digest_method: http://www.w3.org/2001/04/xmlenc#sha256
  signature_method: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256

# vim: set ft=eruby :
