---
# Key users by a Login.gov identifier. By default lookup order is:
# email, uuid, name_id (configure with BROKER_USER_MAP_KEYS).
users:
  gerardo.cruz-ortiz@gsa.gov:
    aws_role: reader    
    session_duration: 3600
    quicksight_groups:
      - team-data
    quicksight_namespaces:
      - fraud-ops
      - delivery

  ambuj.neupane+qs@gsa.gov:
    aws_role: author
    quicksight_groups:
      - team-data
    quicksight_namespaces:
      - fraud-ops

  basilio.bogado@gsa.gov:
    aws_role: author
    quicksight_groups:
      - team-data
    quicksight_namespaces:
      - delivery